### PR TITLE
Append extra bottom slot on the input group component

### PR DESCRIPTION
**Pull request by shankhadevpadam**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| License                 | MIT

#### What's in this PR?

In the current version, there is no option to append any information text. Like this
slot

So after this commit, you can append the information text like this

```php
<x-adminlte-input label="Name" name="name" :value="old('name')">
    <x-slot name="infoSlot">
        <span class="text-sm text-info">[Note: This is extra information.]</span>
    </x-slot>
</x-adminlte-input>
```

#### Checklist

- [x] I tested these changes.
- [x] I have linked the related issues.
- [x] Add documentation on the wiki.

### CODE REVIEW

**Comment by Shidersz** [comment]
@shankhadevpadam Thanks for you contribution, in principle I need to give it a review to check there is no issue with all the components that extends from the `input-group-component` one. On the other hand, I think we should use a more general slot name, since we can use that slot for multiple purposes (not just for add additional information). My current idea is just to name it as **bottomSlot**, but other ideas are accepted.

**Comment by shankhadevpadam** [comment]
Ok thanks.

**Comment by Shidersz** [comment]
@shankhadevpadam I have reviewed and there is no conflict with the components. So, please change slot name from `infoSlot` to `bottomSlot`, since we may use this slot for more general purposes, not just to add extra information. Then I will add the related documentation on the wiki pages and merge this **PR** into master. Thanks!

**Review by resslinger — APPROVED** [review]

**Comment by resslinger** [comment]
@Shidersz I renamed infoSlot to bottomSlot. The PR can be merged.

**Review by Shidersz — APPROVED** [review]

**Pull request merged**
