### PR TITLE
Add feature to change the logo for authentication pages

### PR DESCRIPTION
**Pull request by smarcelloc**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| License                 | MIT

Good evening, I liked the project and wanted to contribute with a small adjustment. I'm sorry! for my english, because i'm brazilian i'm still practicing.

#### Introduction
Possibility to change the logo of the authentication pages in the configuration.

#### Description
Although the framework includes a logo on the screens (login and administrative),  but for the login screen it usually appears an icon or small image representing the logo. In a situation where the developer wants to include a different logo on the login screen (example, logo adapted for screen with background dark or a larger image representing the emblem).  Also, the logo setup is more geared towards the admin screen and sidebar than the login screen.

So I created this pull request that allows the developer to customize a logo image for authentication screens for their customers. If you don't need it, the system will work normally as it was before, without any changes.

#### How does it work?

In the **'auth_logo'** parameter, the developer will choose whether to customize the logo of the authentication screens yes (true) or no (false). In case 'false' the framework will not change the logo and will work as it was before.

- **auth_logo**: render the custom (true) or (false) logo that comes by default. (boolean)
- **auth_logo_img_class**: Add class from css file. (string)
- **auth_logo_img**: image path. (string)
- **auth_logo_img_alt**: alt image. (string)

### Wiki - https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration

How would it look in the framework Wiki with new implementation. 

After the **title** right on the configuration screen. https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#logo

Title: Authenticated Logo

If you want to change the logo of the authentication pages, with Login, Register, Reset Password, etc. You can enable in the `auth_img` parameter set to `true`. 

- **auth_img**: Customize a logo (true) or keep it as default (false)
- **auth_logo_img**:  The path to the logo image.
- **auth_logo_img_class**: Extra classes for the logo image.
- **auth_logo_img_alt**:  The alternate text for the logo images.

### Checklist

- [x] I tested these changes.
- [ ] Add Wiki docs

### CODE REVIEW

**Comment by dfsmania** [comment]
Thanks for the contribution! Please, give us time to test and review it!

**Comment by dfsmania** [comment]
Hi @smarcelloc I will take some more time to think about this **PR**.

Currently, the developer has the possibility to [publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) to cover these situations. Once the views are published, they can made any sort of customization over they (including using a different logo for the authentication views).

The main problem I'm seeing right now is that we going to end up with a very large configuration file if we allow these sort of customizations. Imagine if, in a future, someone wants a different logo for the register page or the password reset page.

By the moment, I will mark this as a draft, while I keep thinking about it...

Thanks!

**Comment by dfsmania** [comment]
@resslinger and @REJack I would love to hear your opinion about this too, when you have some time to check it.

**Comment by resslinger** [comment]
@dfsmania I think this is a good feature, so we can change the logo in a easy way before publishing and editing the views.

**Comment by dfsmania** [comment]
@resslinger OK, I will work on this PR when I get some time, it needs some changes... But I believe, at some point we should stop including so much customization, the configuration file is already too long and the purpose of publishing the views was to cover these customizations cases.

**Comment by resslinger** [comment]
@dfsmania With the ability of customization with config options, we add a flexible way for users. It's easier to maintain a project instead of publishing the views. If an update comes with breaking changes on the views, the local views have to change too. This can be reduce, if we add the flexibility over config options.
I would like prefer to add more blocks / sections into our views instead of publishing views.

**Comment by REJack** [comment]
I like the feature too :D why not splitting config files like splitting out menu and plugins, or all theme based options in a separate config 😄

**Comment by dfsmania** [comment]
@REJack I was thinking about that too for a future, but it will not be backward compatible... It will require the users to rework their config files when updating...

I was also thinking about moving all the config sections to the array-like way (that I was already using for all the new sections).

I think we can do these changes when providing the support to **AdminLTE 4**, since I don't believe there is a way to make that upgrade backward compatible.

**Comment by REJack** [comment]
Yeah thats a good way, even migrating from BS4 to BS5 isn't quite easy since they started with RTL support. So its the best way to force the user reworking the configs.

**Review by dfsmania — APPROVED** [review]

**Comment by dfsmania** [comment]
@resslinger @REJack thanks for your opinions, I have made some changes to the PR, you are both welcome to review it...

**Review by resslinger — APPROVED** [review]

**Pull request merged**
