### PR TITLE
Add thai language in th folder

### PR DESCRIPTION
**Pull request by BazioDEV**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| License                 | MIT

#### What's in this PR?

I have added the thai language for the adminlte.php and still continue on menu

#### Checklist

- [ ] I tested these changes.
- [ ] I have linked the related issues.

### CODE REVIEW

**Review by Shidersz — CHANGES_REQUESTED** [review]
Please, remove the **`.DS_Store`** files

**Review by resslinger — APPROVED** [review]
> Please, remove the **`.DS_Store`** files

done

**Comment by Shidersz** [comment]
Hi @BazioDEV Thanks for your contribution, would you also include translations for the [menu.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/lang/en/menu.php) file example?

**Review by Shidersz — APPROVED** [review]

**Comment by resslinger** [comment]
@BazioDEV please add the translation for the menu.php. Thank you.

**Pull request closed without merging**
