### PR TITLE
Renamed MakeAuthCommand to AuthMakeCommand.

### PR DESCRIPTION
**Pull request by happy-ryo**
Laravel 5.4 it seems there has been a change: MakeAuthCommand has been renamed to AuthMakeCommand.

### CODE REVIEW

**Comment by simik-ru** [comment]
You also need to fix reference to MakeAuthCommand class here:
https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/src/ServiceProvider.php#L95

**Comment by jeroennoten** [comment]
Hmm... I actually would like that it keeps working with older versions of Laravel as well.

**Comment by simik-ru** [comment]
I think this will require making a duplicate class with a different base class, like AdminLteMakeCommand and MakeAdminLteCommand extending respective Laravel classes.
Then in service provider you select the command class to load based on available Laravel base class.

**Comment by jeroennoten** [comment]
Yes! That's a nice approach.

**Comment by jeroennoten** [comment]
Closing in favor of #106

**Pull request closed without merging**
