### PR TITLE
Update run-test workflow

### PR DESCRIPTION
**Pull request by Shidersz**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| License                 | MIT

#### What's in this PR?

Update the github `run-test` workflow with next changes:
- Remove installation of __sqlite3__. I consider this is was not needed, but I may be wrong, please review it.
- Add a new conditional step to upload the code coverage to `scrutinizer-ci`.

#### Checklist

- [x] I tested these changes.

### CODE REVIEW

**Comment by Shidersz** [comment]
@lacodimizer Please, do not merge, it is not working as expected right now.

**Comment by Shidersz** [comment]
@lacodimizer @REJack Code coverage upload is now working from the github workflow, I have added a new conditional test to get executed only under some conditions, as shown next:

```yml
# Upload coverage only for latest versions.
-   name: Upload coverage to scrutinizer-ci
    if: matrix.php == '7.4' && matrix.laravel == '8.*' && matrix.dependency-version == 'prefer-stable'
    run: |
         wget https://scrutinizer-ci.com/ocular.phar
         sleep 30
         php ocular.phar code-coverage:upload --format=php-clover coverage.clover
```

However, it is not syncing with the scrutinizer-ci tool. The reason is that scrutinizer-ci first run a series of tests, and then launch the __waiting for external coverage__ procedure, and at that time the file `coverage.clover` was already uploaded. The only idea I have right now to solve this is by increment the `sleep 30` command to `sleep 120` or something like that. However, it is not a good idea to have a sleep there. Any clue on how to solve this sync problem??

Thanks!

**Comment by Shidersz** [comment]
__New update:__

When the job fetch the package source code, next lines are shown:

```sh
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/716/merge
  Note: switching to 'refs/remotes/pull/716/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at a819a34 Merge bbc31113c44a415c26782fad5df43b6f17ddb245 into ca8ecfa342a7bcc75079405b51aa25b6300bca80
/usr/bin/git log -1 --format='%H'
'a819a34db3785a393d85ad841b9f178377d75536'
```

A few steps later, the coverage is uploaded to:

```sh
Uploading code coverage for repository "g/jeroennoten/Laravel-AdminLTE" and revision "a819a34db3785a393d85ad841b9f178377d75536"... Done
```

But scrutinizer-ci is waiting the feedback for revision:

```sh
bbc31113c44a415c26782fad5df43b6f17ddb245
```

So, feedback is uploaded to wrong revision, __any clue about how to fix this is welcome.__

Also, note that executing same commands from my local environment works as expected:

```sh
vendor/bin/phpunit --coverage-clover=coverage.clover
wget https://scrutinizer-ci.com/ocular.phar
php ocular.phar code-coverage:upload --repository=g/jeroennoten/Laravel-AdminLTE --format=php-clover coverage.clover


#!/usr/bin/env php
Uploading code coverage for repository "g/jeroennoten/Laravel-AdminLTE" and revision "bbc31113c44a415c26782fad5df43b6f17ddb245"... Done
```

**Comment by Shidersz** [comment]
@lacodimizer @REJack Finally solved using [checkout of the pull request HEAD instead of merge the commit](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit). This is ready to go now...

**Comment by REJack** [comment]
👍 Nice work @Shidersz

**Pull request merged**
