### PR TITLE
Adding support for Laravel 6.0

### PR DESCRIPTION
**Pull request by marcosrocha85**

### CODE REVIEW

**Comment by marcosrocha85** [comment]
@lacodimizer this pr is for AdminLTE3. What the plans for AdminLTE3. It will be migrated to Laravel 6?

**Comment by lacodimizer** [comment]
@marcosrocha85 It‘s a good question. I want to give adminlte v3 to Laravel 5 and 6. So I want to create 4 version. Or we drop the support of adminlte v2. What do you think about it?
@REJack Do you support adminlte v2 in the future after release of v3?

**Comment by andcarpi** [comment]
My 2 cents...
Even with BS3 being released in 2011, a lot of people still use It. When admilte3 release a stable version we should encourage people to migrate, but also maintain some kind of support for a period of time... Like... 6months, 1 year. If you automatic drop the v2 support, lot of people can get in throuble, but the problem will be the maintenance of the 4 versions of the package.
On the other side, if v2 really gets dropped from rejack, we can at least make a detailed upgrade guide to help the migration. (But that probably needs to be done in the adminlte repository).

**Comment by marcosrocha85** [comment]
@andcarpi I was about to say that. I use Laraspace in some projects of mine. It uses Bootstrap 4 + Vuejs. Besides Laravel 6 has option to scaffiold pages with Bootstrap or Vue. I think is a good idea to bring AdminLTE2 layout, which is cleaner for me, on bootstrap 4 and vuejs.

**Comment by REJack** [comment]
> @REJack Do you support adminlte v2 in the future after release of v3?

I want to maintaine AdminLTE v2 til mid next year but only with bugfixes & plugin updates, detailed infos come with the v3 stable release.


> @marcosrocha85 It‘s a good question. I want to give adminlte v3 to Laravel 5 and 6. So I want to create 4 version. Or we drop the support of adminlte v2. What do you think about it?

I would create a new major release for AdminLTE v3 for Laravel 5 & 6 and stay with AdminLTE v2 also for Laravel 5 & 6 on a "v1" branch, but that's are only 2 versions in my opinion 😄
I only prefer a new major release for AdminLTE v3 to avoid breaks and the migration from AdminLTE v2 to v3 is not easy.

**Comment by marcosrocha85** [comment]
I closed this pr because my mistake of merging master to develop. Btw, only file I fixed here was composer.json to support Laravel 6.0 and LangFilter to support both Laravel 5.x and 6.0 translations.

**Pull request closed without merging**
