### PR TITLE
Translate menu items using lang files

### PR DESCRIPTION
**Pull request by Anpix**
This improvement help to use lang files to translate menu itens.
I just make the EN and PT-BR translation files.

All the instructions was commited in Readme.md

### CODE REVIEW

**Comment by jeroennoten** [comment]
Wow this is nice! I really really appreciate this PR and I will accept it for sure. However there are two issues now:

- With this implementation it is not possible to have non-translated header items. So I would suggest something like `header_lang` instead of `header` as key and only translate that one.

- I am not a fan of the requirements to put the language files in the `vendor` dir, because that suggests that the translations are a customizable default. My suggestion would be to let the user indicate the full language key, e.g. `menu.profile`, then the user can just put it in `lang/menu.php`, but they can also use a translation key that is already in use by their application.

Could you make these two changes? Thanks!

Then a few things that I was just considering, but not yet decided...
- Is `lang` the right terminology or `trans` be better?
- How about the (additionally) new way of translation in Laravel 5.4: https://laravel.com/docs/5.4/localization#using-translation-strings-as-keys

Not sure about these two things...

**Comment by Anpix** [comment]
Thanks, @jeroennoten.

### 1) Header Translation
> With this implementation it is not possible to have non-translated header items. So I would suggest something like `header_lang` instead of `header` as key and only translate that one.

Sure! this was my fault. The secound line of the file `menu-item.blade.php` should be:

```php
<li class="header">{{ $item }}</li>
```
instead
```php
<li class="header">{{ trans('adminlte::menu.'.$item) }}</li>
```

That way get the string directly sent by `$item` variable.

**Question:** Should we keep the check of `header` sugested ahead, or is better force the use of `header` or `header_lang` param?
I think that is better keep the header as String (without `header` param) when using not-translated headers. But, for translated header, just use the `header` param.

**Comment by jeroennoten** [comment]
Well, we already need the `header` key for header text when you want to add the `can` option (see https://github.com/jeroennoten/Laravel-AdminLTE#51-menu), so therefore my preference for `header_lang`. Otherwise one cannot have non-translated header items with `can` attribute.

**Comment by jeroennoten** [comment]
Oh and bonus points if you add unit tests 😉

**Comment by Mopster** [comment]
I'm needing this for my new bilingual project :-) any forecast on when it'll be merged ?

**Comment by zcwilt** [comment]
I have another approach which might be simpler.
Currently working on a filter class that does language translation for menu items 
Have a filter that looks like

```
namespace JeroenNoten\LaravelAdminLte\Menu\Filters;

use JeroenNoten\LaravelAdminLte\Menu\Builder;
use Illuminate\Contracts\Translation\Translator;
class LangFilter implements FilterInterface
{
    protected $langGenerator;
    public function __construct(Translator $langGenerator)
    {
        $this->langGenerator = $langGenerator;
    }
    public function transform($item, Builder $builder)
    {
        if (isset($item['header'])) {
            $item['header'] = $this->langGenerator->trans($item['header']);
        }
        if (isset($item['text'])) {
            $item['text'] = $this->langGenerator->trans($item['text']);
        }
        return $item;
    }
}
```

The pluses are backward compatibility, no need to change menu array format, apart from having to explicitly use a `header` entry.

Will try and work up a PR with tests if you think it is a good idea.

**Comment by zcwilt** [comment]
Just a note, my test menu config looks like

```
    'menu' => [
        [
            'header' => 'dashboard.bannersheader',
        ],
        [
            'text' => 'dashboard.bannersentry',
            'url' => 'banners',
        ],
        [
            'text' => 'dashboard.bannersgroupentry',
            'url' => 'bannerGroups',
        ],
        [
            'header' => 'Reports',
        ],
        [
            'text' => 'dashboard.reportclicksentry',
            'url' => 'clicks',
        ],
        [
            'text' => 'dashboard.reportimpressionsentry',
            'url' => 'impressions',
        ],

    ],
```
so you can reference any language config, and stuff that is not translated like the 

```
 'header' => 'Reports',
```

will just be displayed as normal,

**Comment by leonelelizondo** [comment]
Hello friends, I am using this template in laravel and I need to know how to add middlewards to the menu. To show only what is necessary for each user role.

**Pull request merged**
