### PR TITLE
Fix make:adminlte for Laravel 5.4.31+

### PR DESCRIPTION
**Pull request by simik-ru**

### CODE REVIEW

**Comment by mushroomgroover** [comment]
Thank you! @simik-ru 
I also found out this was mentioned in #102

**Comment by Lvkz** [comment]
@jeroennoten This fix works.

**Comment by regiszanandrea** [comment]
Please, accept this pull request!

Thanks @simik-ru

**Comment by jeroennoten** [comment]
Thanks for this PR and sorry for the delay!

**Pull request merged**
