### PR TITLE
Add bootstrap style to datatables

### PR DESCRIPTION
**Pull request by Tropicalista**

### CODE REVIEW

**Comment by Tropicalista** [comment]
Please can you merge this?

Thanks

**Comment by ahinkle** [comment]
Ever think that it would break others projects using the other version? This package is a boilerplate to support the majority - if you have your own needs you can modify this in your own repo.

**Comment by Tropicalista** [comment]
AdminLte is based on bootstrap. So I don't see how it will breaks other version.

**Comment by loekiedepo** [comment]
> Ever think that it would break others projects using the other version? This package is a boilerplate to support the majority

That said, should we even be including JavaScript assets via config? @jeroennoten made sure to delete all the included ones in the official AdminLTE template, so why are they here anyway? Just asking, I never use them so I don't mind them. But I can imagine this growing into a jungle of JS assets as this package is getting more attention lately.

**Comment by ricardovigatti** [comment]
This will be merged?

**Comment by ricardovigatti** [comment]
Related to #61 ?

**Comment by jeroennoten** [comment]
Fixed in #229.

**Pull request closed without merging**
