### PR TITLE
Display unescaped data on input field.

### PR DESCRIPTION
**Pull request by shankhadevpadam**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| License                 | MIT

#### What's in this PR?

There is an issue while displaying a string with quotes in the input field. For eg if I want to display data like "29 O'Dea Street" in the input field.

```php
<x-adminlte-input label="Address 1" id="address_1" name="address_1" :value="old('address_1', $order->billing->address_1)" />
```
Its output is like this
Screenshot

After this pr, if we pass the is-escaped attribute in the input tag.
```php
<x-adminlte-input label="Address 1" id="address_1" name="address_1" :value="old('address_1', $order->billing->address_1)" :is-escaped="false" />
```
Its output is like this

Screenshot (1)
#### Checklist

- [x] I tested these changes.
- [x] I have linked the related issues.

### CODE REVIEW

**Comment by dfsmania** [comment]
Thanks, give me some time to review this!

**Comment by dfsmania** [comment]
Hi @shankhadevpadam I think there is no need to make the underlying component more complex...

You can declare your input field as:

```blade
<x-adminlte-input label="Address 1" id="address_1" name="address_1" value="{!! old('address_1', $order->billing->address_1) !!}" />
```

Please, try it...

**Review by dfsmania — COMMENTED** [review]
No need to make changes, the user can choice to `unescape` data inside the value attribute.

**Comment by shankhadevpadam** [comment]
Thanks, @dfsmania  don't need this pull request.

**Pull request closed without merging**
