### PR TITLE
Fix active filter for urls with query string

### PR DESCRIPTION
**Pull request by lacodimizer**

### CODE REVIEW

**Comment by mwoszczyna** [comment]
I believe the latest changes (v. 3.2) broke some of the active menu items features.
As per this release the navigation menu active checker doesn't work well with submenu urls like:
'/b/method?status=0' and it doesn't highlight the menu path as before.

FYI  previous version (3.1.1) seems to be fine and  menu works as expected.

**Comment by lacodimizer** [comment]
@mwoszczyna Can you send us your menu config?

**Comment by mwoszczyna** [comment]
Sure mate, I've sent it to florian@[...].de e-maili.

**Comment by chijinbo** [comment]
The change in the function "checkPattern" break the activeCheker for submenu. 
image

**Comment by lacodimizer** [comment]
@chijinbo please open an issue with more details, like your menu config and the provided informations in the issue template.

**Comment by Shidersz** [comment]
@lacodimizer @chijinbo Note that is an old version of the source code, the current code is far away from that version. @chijinbo is there any reason for you to not use the latest version of the package?

**Comment by chijinbo** [comment]
Hi @lacodimizer @Shidersz 

I just updated from V3.1.1 to the latest version, the change in the CheckPattern (fullUrl() to url()) broken the active check on the menu item with the query string. 

The same issue like mwoszczyna mentioned in April, if the menu URL is "/b/method?status=0", then the activeChecker won't mark it as active.

My menu config is like:

> [
            'text'        => 'Test',
            'url'         => '/tests',
            'icon'        => 'fas fa-envelope',
            'active' => ['/tests','/tests/*'],
        ],
        [
            'text'        => 'Test Query',
            'url'         => '/tests?includedTypes[]=Query',
            'icon'        => 'fas fa-cogs',
            'active' => ['/tests?includedTypes*=Query'],
        ]

Cheers

**Comment by Shidersz** [comment]
@chijinbo Please open an issue explaining your problem with details. However, is there any reason you can't just do:

```
[
'text' => 'Test Query',
'url' => '/tests?includedTypes[]=Query',
'icon' => 'fas fa-cogs',
'active' => ['/tests'],
]
```
Why you need to match query parameters on the url?
Do you have multiple menu items pointing to the same base url, but with different query parameters?

**Pull request merged**
