### PR TITLE
Add Blade-x components

### PR DESCRIPTION
**Pull request by resslinger**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| License                 | MIT

#### What's in this PR?

This PR include the Blade-x components from https://github.com/dgvai/laravel-adminlte-components

Thank you very much @dgvai for the great work and for the permission, to include this directly in this project. 

#### Checklist

- [ ] I tested these changes.
- [x] I have linked the related issues.

### CODE REVIEW

**Comment by dgvai** [comment]
What if I update something in my package, will I have to create PR here for the changes too?

**Comment by lacodimizer** [comment]
@dgvai Or you make only the changes into these package. The other package is not needed after this merge.

**Comment by Shidersz** [comment]
A few tips:

- Maybe you can use `namespace` to register all the components:
  ```php
  /**
   * Bootstrap your package's services.
   */
   public function boot()
  {
      Blade::componentNamespace('Nightshade\\Views\\Components', 'nightshade');
  }
  ```
  Reference: https://laravel.com/docs/8.x/blade#components

- Maybe there is a way to conditionally include components depending on the Laravel version, so we don't have to drop Laravel 6 version.

**Comment by Shidersz** [comment]
Sorry, `componentNamespace()` is only available for Laravel versions >= 8.x. :disappointed:

**Comment by Shidersz** [comment]
@lacodimizer @dgvai I created PR #724 to check the Laravel support before trying to include the components. This may help to keep the support for Laravel 6.x versions. You can discard it in the case you want to drop that support.

We still need to make a minimal set tests for the components, I'm going to check for a way to do this on next days.

**Comment by Shidersz** [comment]
@lacodimizer @dgvai I found a problem while testing the components on my local environment. Every component class have a `render()` method, for example:

```php
public function render()
{
    return view('adminlte::input');
}
```

But the `adminlte::input` view is not found. We have two ways to solve this:

1. Move the `resources/components` folder to `resources/views/components` and then change all the `render()` methods like this:
   ```php
   public function render()
   {
       return view('adminlte::components.input');
   }
   ```

2. Load the `resources/components` views in the service provider using something like next on the `loadComponents()` method:
   ```php
   $viewsPath = $this->packagePath('resources/components');
   $this->loadViewsFrom($viewsPath, 'adminlte-component');
   ```
   And then, again, change all the render methods like this:
   ```php
   public function render()
   {
       return view('adminlte-components::input');
   }
   ```

Which one you prefer?

**Comment by lacodimizer** [comment]
@Shidersz I would prefer the first option, so we have a standard, like the other blade includes. But the second option is good too.

**Comment by Shidersz** [comment]
@lacodimizer Ok, I'm going to add those changes to my current PR.

**Comment by Shidersz** [comment]
@dgvai @lacodimizer While I was making some tests for the components, I figure out that we can do some enhancements on some of they before the first release. Why before the first release? Because changing the interface after first release will generate a greater impact on the people that uses they. If you all agree, I can create an issue and share the ideas there.

**Comment by Shidersz** [comment]
Nice, workflows are working, we have a setup to run component tests when Laravel version is 7+ and avoid those tests on Laravel 6.x versions. I will upload the first component improvement soon...

**Comment by Shidersz** [comment]
@resslinger Any idea why `styeci` and `scrutinizer` do not show for the last commit?

**Pull request merged**
