### PR TITLE
remove card header if title not exists

### PR DESCRIPTION
**Pull request by shankhadevpadam**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| License                 | MIT

#### What's in this PR?

If the title does not exist. It removes the card header.

#### Checklist

- [x] I tested these changes.
- [x] I have linked the related issues.

### CODE REVIEW

**Comment by Shidersz** [comment]
I'm not sure about this. You can have only an **Icon** on the title, or just the button tools to collapse, maximize, etc. I will give a better review later.

**Review by Shidersz — CHANGES_REQUESTED** [review]
Please, remove the two `.phpintel/files` you have added.

**Comment by Shidersz** [comment]
After a review, I think the best way to implement this will be to control all the elements of the header (`title`, `icon`, and `button tools`) are not used in order to remove/hide it. I will work on this later to get done that way. However, I can't still imagine an use case without the header, do you have any example to share?

**Comment by Shidersz** [comment]
@shankhadevpadam I have made some work on the component so the body / header are not shown when there is no data for they. At next you can see examples:

```blade
<div class="row">

    {{-- Minimal with a title --}}
    <div class="col-md-4">
        <x-adminlte-card title="A card without body"/>
    </div>

    {{-- Minimal without header --}}
    <div class="col-md-4">
        <x-adminlte-card theme="lime" theme-mode="outline">
            A card without header...
        </x-adminlte-card>
    </div>
</div>
```

Screenshot_2021-05-24 Laradmin Tests

Please, review and tell me if you are ok with these changes.

Also, next time please create a new **branch** for your changes (do not use `master` branch). Read [contribution guidelines](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/.github/CONTRIBUTING.md) for more information.

**Review by Shidersz — APPROVED** [review]

**Comment by shankhadevpadam** [comment]
@Shidersz sorry for the direct push into the master branch. One use case is like this

Screenshot

**Review by resslinger — APPROVED** [review]

**Comment by Shidersz** [comment]
@shankhadevpadam Ok, thanks for sharing it. Just tell me if you agree with the changes I have made.

**Comment by shankhadevpadam** [comment]
@Shidersz still there is a border above the card body. I think plane one is sweet. Which the pr generate. 🙂🙂🙂

**Comment by Shidersz** [comment]
@shankhadevpadam What border? I don't understand what you mean?

**Comment by shankhadevpadam** [comment]
@Shidersz lime one. 😀😀😀

**Comment by Shidersz** [comment]
That is because I explicitly added the  `theme="lime" theme-mode="outline"` to the component, these are supported properties of the component. Check [documentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Widget-Components#card)...

**Comment by shankhadevpadam** [comment]
Ok thanks @Shidersz

**Pull request merged**
