### PR TITLE
Drop support for Laravel 6

### PR DESCRIPTION
**Pull request by resslinger**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| License                 | MIT

#### What's in this PR?

This PR drops the support for Laravel 6.

Laravel 6 outdated since September 6th, 2022

(https://laravel.com/docs/9.x/releases)

#### Checklist

- [x] I tested these changes.
- [ ] Update README to explain these changes.

### CODE REVIEW

**Review by dfsmania — COMMENTED** [review]
I will keep this support, at least for `Laravel 7` versions...

**Comment by resslinger** [comment]
Hi @dfsmania thank you! :)

I would prefer to only support Laravel versions until there are no more security updates. Like Laravel 6 + 7.
We only drop the support for Laravel < 8 for new releases.

But we can drop support for Laravel 6 + 7 on the new minor release 3.9 oder next major release 4.x.
I think, that's a good way.

**Comment by dfsmania** [comment]
Ok, we can keep this as a draft for the future...

**Comment by dfsmania** [comment]
@resslinger If you agree, I think we can rework this PR to drop support just for **Laravel 6** and keep the support to **Laravel 7** for a while... What do you think?

On the other hand, after this task has been done, we may add support to run tests on **Laravel 10** with a new PR.

**Comment by dfsmania** [comment]
@resslinger Sorry, I broke this one. I will start another PR for these changes...

**Comment by dfsmania** [comment]
Moved to #1178

**Pull request closed without merging**
