### PR TITLE
Add Vietnamese to adminlte and confirm adminlte work with laravel 6.0 

### PR DESCRIPTION
**Pull request by xuandung38**
Add Vietnamese to adminlte and confirm adminlte work with laravel 6.0

### CODE REVIEW

**Comment by lacodimizer** [comment]
Hi, do you have checked the compatibility with laravel 6?

**Comment by xuandung38** [comment]
I used adminlte with laravel 5.8 and I tried laravel update to 6.0, everything works very well

**Comment by REJack** [comment]
What you changed inside the resources/assets/dist/js/adminlte.min.js?

**Comment by xuandung38** [comment]
> What you changed inside the resources/assets/dist/js/adminlte.min.js?

Nothing change. you can see

**Comment by lacodimizer** [comment]
> What you changed inside the resources/assets/dist/js/adminlte.min.js?

@REJack The file was not merged with the current master...

**Pull request merged**
