### PR TITLE
Add Navbar Menu Item: Dark Mode

### PR DESCRIPTION
**Pull request by BIhab**
| Question                | Answer
| ----------------------- | -----------------------
| Enhancement    | Enhancement
| License                 | MIT

#### What's in this PR?

Add support to a new menu item that represents a dark mode toggle widget for the top navbar in relation to pull request #893 that includes a new configuration option to enable/disable dark mode permanently.

```php
[
    'type'         => 'darkmode-widget',
    'topnav_right' => true, // Or "topnav => true" to place on the left.
],
```

Also, you can setup next optional properties to customize the icons and the colors to use:

- `'icon_enabled'`: The Font Awesome icon to use when darkmode is enabled (`'fas fa-moon'` by default).
- `'icon_disabled'`: The Font Awesome icon to use when darkmode is disabled (`'far fa-moon'` by default).
- `'color_enabled'`: The AdminLTE color to use for the icon when darkmode is enabled.
- `'color_disabled'`: The AdminLTE color to use for the icon when darkmode is disabled.

Additional fix:

- The `getPackageServiceProvider()` method used on multiple test cases was moved to the base `TestCase.php` file.

#### Behaviour Explained

- An underlying blade component is used to display/render the widget.
- When the widget and layout is rendered, the dark mode preference will be search on a session's special key in order to show the correct icon and layout style. If there is no session key, it will fallback to the value from the configuration file.
- When the widget is clicked, the widget icon and the body class will be toggled on the client side in order to show a dark mode toggle effect. Also, a post to an underlying controller will be triggered. The controller will be in charge to update the session key value, and to trigger a special event. Then, an end user can listen to this event in order to get the new dark mode status value. This way, he will have the facility to register a callback in order to store the preference on a database (maybe per user, for example).
- The underlying controller will also provide some methods (`enable()`, `disable()`) to setup the dark mode status. The idea is that an end user can invoke these methods when listening on another special event (`ReadingDarkModePreference`) on the `boot()` method of the `EventServiceProvider` in order to setup the initial state, after reading the preference from a database, for example.

#### Example of `app/Providers/EventServiceProvider`

This is an example of the logic needed on the `EventServiceProvider` of your Laravel application in order to interact with the dark mode widget. The example assumes the dark mode preference is stored per user basis.

```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Log;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;
use JeroenNoten\LaravelAdminLte\Events\DarkModeWasToggled;
use JeroenNoten\LaravelAdminLte\Events\ReadingDarkModePreference;

class EventServiceProvider extends ServiceProvider
{
    ...
 
    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        // Register listener for ReadingDarkModePreference event. We use this
        // event to setup dark mode initial status for AdminLTE package.

        Event::listen(
            ReadingDarkModePreference::class,
            [$this, 'handleReadingDarkModeEvt']
        );

        // Register listener for DarkModeWasToggled AdminLTE event.

        Event::listen(
            DarkModeWasToggled::class,
            [$this, 'handleDarkModeWasToggledEvt']
        );
    }

    /**
     * Handle the ReadingDarkModePreference AdminLTE event.
     *
     * @param ReadingDarkModePreference $event
     * @return void
     */
    public function handleReadingDarkModeEvt(ReadingDarkModePreference $event)
    {
        // TODO: Implement the next method to get the dark mode preference for the
        // current authenticated user. Usually this preference will be stored on a database,
        // it is your task to get it.

        $darkModeCfg = $this->getDarkModeSettingFromDB();

        // Setup initial dark mode preference.

        if ($darkModeCfg) {
            $event->darkMode->enable();
        } else {
            $event->darkMode->disable();
        }
    }

    /**
     * Handle the DarkModeWasToggled AdminLTE event.
     *
     * @param DarkModeWasToggled $event
     * @return void
     */
    public function handleDarkModeWasToggledEvt(DarkModeWasToggled $event)
    {
        // Get the new dark mode preference (enabled or not).

        $darkModeCfg = $event->darkMode->isEnabled();

        if ($darkModeCfg) {
            Log::debug("Dark mode preference is now enabled!");
        } else {
            Log::debug("Dark mode preference is now disabled!");
        }

        // Store the new dark mode preference on the database.

        $this->storeDarkModeSettingOnDB($darkModeCfg);

        // TODO: Implement previous method to store the new dark mode
        // preference for the authenticated user. Usually this preference will
        // be stored on a database, it is your task to store it.
    }
}
```

#### Note to the Community

_Any feedback or help from the community is required in order to improve this mechanism. Currently, I can't see any way to simplify this logic and provide a sort of persistent storage for the dark mode preference._

#### Checklist

- [x] I tested these changes.
- [x] I have linked the related issues.
- [x] Add tests related to the new component.
- [x] Add controllers/routes to catch a request for change the dark mode underlying configuration.
- [x] Trigger an event when dark mode is toggled.
- [x] Add tests related to the new controllers/routes/events.
- [x] Add wiki documentation.
- [x] Update documentation.

### CODE REVIEW

**Comment by Shidersz** [comment]
@BIhab Thanks for your contribution, this is one idea I had in mind to include in this package, it is welcome! However, I need to review some things:

- Intead of using the local storage to save dark mode state, we need to read the related package configuration option, and maybe save new state there also, rewriting the config value.
- We are projecting to implement all the menu item with laravel blade components on the future, so we are trying to implement new items with components, to serve as a guide later.

I will try to rework this PR to meet previous objetives. Then we can merge this one. Thanks you!

**Comment by Shidersz** [comment]
@BIhab @resslinger I have invested some time, and so far I see the next possibilities for this dark mode toggle widget:

1. We just implement the widget to toggle the `dark-mode` class on the `<body>` tag. Nothing will be saved, for a new request the dark mode state will be the one configured on the `adminlte.php` file. Thus, the dark mode state won't be remembered between subsequent requests. This is the easiest solution...

2. It is possible to store the dark mode status under a session key (for example, using `session(['adminlte_dark_mode' => state]);`) and read it back from the session on each request to setup the correct class on the body and the correct button style. This way we can remember the dark mode state between subsequent requests. However, this solution requires new controllers/routes on the package, and an `ajax` request from the client side to the server in order to change the dark mode session value.

Now, on a real project, these type of preferences are usually saved on a database and related to the user. To get further with **solution 2** we can implement calls to `Auth::user()->adminlte_getDarkmode()` and `Auth::user()->adminlte_setDarkmode()` on the controller that handles the darkmode when these methods exists. That way an end user has the possibility to implement these methods on the **user model** to store/read information on/from the database. We already do something similar for user image, description, etc. Check [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#user-menu).

What do you think? Go for the easy or hard way?

**Comment by BIhab** [comment]
@Shidersz I see there is a lot of improvement you did from the last time, to answer your question, without any doubt, the hardest way, if we gonna make it, let make perfectly, I'll try to do it this week, thanks for your hard work mate.

**Comment by Shidersz** [comment]
@blhab Don't worry, I'm already on it, I have most of the work done, just want to know your opinions, and maybe your reviews when done. The improvements I have already done are:
- Use of a blade component for the darkmode widget.
- Possibility to change icons and colors.
- Read the initial state from the package configuration value. This will be use as the default fallback state.

**Comment by Shidersz** [comment]
@BIhab @reslinger I want to share the idea I have in mind and I was working on for this feature:

- An underlying blade component will be used for this widget (already done).
- When widget is displayed by first time, it will try to read dark mode preference from a session special key in order to show the correct icon. When there is no session key, it will fallback to value from configuration file.
- When the widget is clicked, the icon and body classes will be toggled to show the dark mode or not. Also a post to a underlying controller will be triggered. The controller will be in charge to update the session key value, and to trigger a special event. Then, an end user can listen to this event in order to get the new dark mode status value. This way, he will have the facility to register a callback in order to store the preference on a database (maybe per user, for example).
- The underlying controller will also provide some methods (`enable()`, `disable()`) to setup the dark mode status. The idea is that an end user can invoke these methods on the `boot()` method of the `AppServiceProvider` in order to setup the initial state, after reading the preference from a database.

I will upload some of the code soon. Also, any feedback or help to improve this mechanism will be welcome. Currently I can't see any way to simplify this logic and provide a sort of persist feature for the dark mode preference.

**Review by Shidersz — APPROVED** [review]

**Comment by Shidersz** [comment]
@BIhab @resslinger Please review the behaviour and logic. When approved, if no changes required, I will create the documentation and finally merge.

**Comment by Shidersz** [comment]
I have discover some issue, I need to fix this before ready for review...

**Comment by Shidersz** [comment]
@resslinger I have tested the mechanism to interact with a database and got it working on my local environment now. If you agree with all the logic, I just wait for your review to include this one into master.

**Comment by resslinger** [comment]
I will give a review in the next days.

**Comment by Shidersz** [comment]
@resslinger Nice, documentation of usage is available [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Special-Menu-Items#navbar-darkmode-widget)

**Review by resslinger — APPROVED** [review]

**Comment by resslinger** [comment]
@Shidersz approved. Good work!

**Pull request merged**
