### PR TITLE
Migration to AdminLTE v3.0

### PR DESCRIPTION
**Pull request by REJack**
I've updated the config, assets, all views and ClassesFilter & SubmenuFilter to use AdminLTE v3.0.0-rc.1.

__My config changes:__
- removed `logo_mini`
- created `logo_img_class`
- created `logo_img_xl`
- created `logo_img_xl_class`
- created `logo_img_alt`
- removed `skin`
- removed `layout`
- created `layout_topnav`
- created `layout_boxed`
- created `layout_fixed_sidebar`
- created `layout_fixed_navbar`
  - boolean or array for responsive uses (e.g. `['xs' => true, 'md' => false]` fixed navbar only for xs & sm)
- created `layout_fixed_footer`
  - boolean or array for responsive uses like `layout_fixed_navbar`
- renamed `body_class` to `classes_body`
- created `classes_brand` (to override brand color)
- created `classes_sidebar` (to override sidebar color style)
- created `classes_sidebar_nav` (to use child ident)
- created `classes_topnav` (to override navbar color style)
- created `classes_topnav_container` (to switch between cotainer & cotainer-fluid in top-nav)
- renamed `collapse_sidebar` to  `sidebar_collapse`
- created `sidebar_mini`
- created `sidebar_collapse_auto_size`
- created `sidebar_collapse_remember`
- created `sidebar_collapse_remember_no_transition`
- created `sidebar_scrollbar_theme`
- created `sidebar_scrollbar_auto_hide`
- created `sidebar_nav_accordion`
- created `sidebar_nav_animation_speed`
- created `right_sidebar_push`
- created `right_sidebar_scrollbar_theme`
- created `right_sidebar_scrollbar_auto_hide`

I've also added support for multi level top nav items.

Idk but I think this should a new mayor version 😄, right?

### Missing Stuff
- [x] new config section in README.md with all config options
- [x] text for extra classes section
- [x] fix test
- [x] fix ci
- [x] logo img with config
- [x] new options from AdminLTE v3
  - sidebar 
    - [x] scrollbar
    - [x] nav animation speed
    - [x] collapse remember 
      - [x] no transition after reload
    - [x] screen collapse size
    - [x] auto collapse
  - [x] controlsidebar scrollbar

### Extra
- Added ability add topnav items with sidebar together instead of topnav layout only
- Added ability to load plugins via blade files
- Added `content_top_nav_right` & `content_top_nav_left` sections in page.blade.php

### Bugs
- Content height wrong without footer 
  - fix comes with v3.0.0-rc.2
- Search Forms in Sidebar look not correct
  - fix comes with v3.0.0-rc.2

### Changes
- updated assets to v3.0.0-rc.1
  - updated dist/css & dist/js (AdminLTE)
  - updated vendor/bootstrap
  - updated vendor/jquery
  - replaced vendor/font-awesome with fontawesome-free
  - replaced plugins/iCheck with icheck-bootstrap
  - added vendor/popper
  - added vendor/overlayScrollbars
  - removed vendor/Ionicons
- moved icheck-bootstrap to vendor/ instead of plugins/ 
- updated views for v3
  - updated config
  - updated views
  - updated ClassesFilter & SubmenuFilter
- updated default config variables
- added control sidebar options 
- fixed ClassesFilter & fixed BuilderTest 
- enhanced views & config for new AdminLTE options
  - added yield body_data in master.blade
  - updated page.blade
  - updated config/adminlte.php
- added logo img
  - updated config/adminlte
  - updated page.blade
  - added AdminLTE logo (A)
- fixed testTreeviewClass in BuilderTest
- added ability to use two image logos instead of a image with text
- enhanced layout config options
  - added extra class info text in config
  - created `layout_topnav` config option
  - created `layout_boxed` config option
  - created `layout_fixed_sidebar` config option
  - created `layout_fixed_navbar` config option
  - created `layout_fixed_footer` config option
  - created `sidebar_mini` config option
  - added new config options in page.blade.php
- enhanced search form
  - updated search form in menu-item.blade.php
  - added search form in menu-item-top-nav.blade.php
- enhanced menu config with topnav option
  - updated config (menu is on topnav)
  - updated menu-item.blade.php
  - updated menu-item-top-nav.blade.php
  - updated page.blade.php
- added ability to use right_sidebar with layout_topnav 
- renamed class related config options
  - renamed `body_class` to `classes_body`
  - renamed `brand_classes` to `classes_brand`
  - renamed `sidebar_classes` to `classes_sidebar`
  - renamed `sidebar_nav_classes` to `classes_sidebar_nav`
  - renamed `topnav_classes` to `classes_topnav`
  - renamed `topnav_container` to `classes_topnav_container`
  - updated views
- updated home.stub
- removed skin load from page.blade.php
- updated comments in config/adminlte.php
- big readme change and some little changes
  - reworked readme with complete config infos
  - created `right_sidebar_push` option
  - removed `adminlte.sidebar_collapse_screen_collapse_size` option
  - added ability to use sidebar-mini-md with sidebar_mini option
  - added ability for `right_sidebar_push`
  - removed ability from `adminlte.sidebar_collapse_screen_collapse_size`
- added ability to enable plugins inside blade files
  - disabled plugins by default (reduce load times)
  - added hasSection check in plugins.blade.php
  - updated README.md with changed infos
- added missing spaces in page.blade.php
- added content_top_nav_right & content_top_nav_left sections in page.blade.php
- added adminlte.min.js loading in login/register/passwords views

### CODE REVIEW

**Comment by lacodimizer** [comment]
@REJack greeeeat!

**Comment by REJack** [comment]
@lacodimizer 
One big question, should I add complete info text for my changed stuff inside the config or should I add a new section in README.md with the info text. May we should create a real documentation 😄 

> Split topnav menu with sidebar menu or add extra topnav menu array if sidebar menu is enabled

And what you think about my idea?

**Comment by REJack** [comment]
@lacodimizer What you think about to rework the `layout` config option, AdminLTE v3 comes with alot class options like sidebar fixed responsive, fixed navbar incl responsive, fixed footer incl responsive. I would split it to `layout_topnav`, `layout_boxed` and create multiple config options for fixed sidebar, navbar & footer and a way to config the responsiv options. Also the boxed layout can be used with fixed sidebar, navbar or footer.

**Comment by lacodimizer** [comment]
@REJack I think we should create a complete readme with all the options, that we can set on the config file. If we begin to add the info into the config file, we have a big config file at the end. The first touch point should be the readme. The mix of a full and complete readme and a small introduction in the config file will be a good way. :)

For new layout options, I think it's a good idea to add more config options to add a new way for customizing, like your example. 👍

**Comment by REJack** [comment]
@lacodimizer I've changed the config and I'm near to done, now I need only to update the README.md, may you find some time to test it 😄

**Comment by lacodimizer** [comment]
@REJack very nice! I will test it in this week. :muscle:

**Comment by REJack** [comment]
@lacodimizer I looked over my code changes while updating the readme and found one possible change in the config, to get a more consistently config file we should change the old `body_class` and all the new created options for classes should start with classes_ instead of ending or not ending 😄 

Like this
```php
    'classes_body' => '',
    'classes_brand' => '',
    'classes_sidebar' => 'sidebar-dark-primary elevation-4',
    'classes_sidebar_nav' => '',
    'classes_topnav' => 'navbar-white navbar-light',
    'classes_topnav_container' => 'container',
```

instead of this
```php
    'body_class' => '',
    'brand_classes' => '',
    'sidebar_classes' => 'sidebar-dark-primary elevation-4',
    'sidebar_nav_classes' => '',
    'topnav_classes' => 'navbar-white navbar-light',
    'topnav_container' => 'container',
```

**Comment by lacodimizer** [comment]
@REJack perfect!

**Comment by REJack** [comment]
I've changed the config options and some other little stuff 😄 

Can I rearrange the readme Configuration points? I would order them like the config order is e.g. 6.1 Title, 6.2 Logo and so on.

**Comment by lacodimizer** [comment]
@REJack at any time. Nice to have - we add the readme link in the sections in config file to get the long description and examples of the config. Whats your plan? 🤔

**Comment by REJack** [comment]
@lacodimizer 
> we add the readme link in the sections in config file to get the long description and examples of the config.

What you mean with that, replacing the descriptions in the config with readme links?

**Comment by lacodimizer** [comment]
@REJack I mean, we remove the long descriptions in the config file, add a short description and add a link to the complete description, which is shown in the readme. I think, if I want to config the project, the first touchpoint should be the readme, not the config file.

**Comment by REJack** [comment]
@lacodimizer Ok I understand, that's a good point. I'll change this with my readme changes.

**Comment by REJack** [comment]
@lacodimizer I've updated the readme and config, also I found some little changes you can check it out 😄

**Comment by REJack** [comment]
@lacodimizer I've added missing spaces in the page blade and added a abilty to load plugins from blade files 😄

**Comment by REJack** [comment]
@lacodimizer Thanks for fixing the travis-ci error 😄

**Comment by lacodimizer** [comment]
@REJack no problem :D

**Pull request merged**
