### PR TITLE
Translations to brazilian portuguese and spanish

### PR DESCRIPTION
**Pull request by LuizToni**
Support for Portuguese and Spanish available out of the box.

### CODE REVIEW

**Comment by jeroennoten** [comment]
Thank you very much!

**Comment by LuizToni** [comment]
Your Wellcome =) 
Ops, I forgot to translate the line number 10 in file es/adminlte.php,   should be  'register' => 'Registre'

**Comment by jeroennoten** [comment]
Could you make a new PR for that?

**Comment by LuizToni** [comment]
Yes, the updated file in a new commit

**Pull request merged**
