### PR TITLE
Add Laravel 9 support

### PR DESCRIPTION
**Pull request by resslinger**
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| License                 | MIT

#### What's in this PR?

This PR add support for Laravel 9.

#### Checklist

- [x] I tested these changes.
- [ ] I have linked the related issues.

### CODE REVIEW

**Comment by Shidersz** [comment]
@resslinger I think we should also change:

```yml
# Upload coverage only for latest versions.
-   name: Upload coverage to scrutinizer-ci
    if: matrix.php == '7.4' && matrix.laravel == '8.*' && matrix.dependency-version == 'prefer-stable'
    run: |
      vendor/bin/phpunit --testsuite Laravel7+ --coverage-clover=coverage.clover
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
```

by

```yml
# Upload coverage only for latest versions.
-   name: Upload coverage to scrutinizer-ci
    if: matrix.php == '8.1' && matrix.laravel == '9.*' && matrix.dependency-version == 'prefer-stable'
    run: |
      vendor/bin/phpunit --testsuite Laravel7+ --coverage-clover=coverage.clover
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
```

to keep uploading coverage only for latest versions...

**Review by Shidersz — APPROVED** [review]

**Comment by Shidersz** [comment]
Well, now we may follow fixes provided on next links as reference:
- https://github.com/scrutinizer-ci/ocular/issues/51
- https://github.com/jmikola/geojson/commit/4f37af3213996a619edc6b02518fb3311aed538a

Or keep uploading coverage with previous versions until `ocular.phar` is fixed...

**Comment by resslinger** [comment]
@Shidersz scrutinizer/ocular has actually no support for Symfony 6. I wait for a answer from scrutinizer.

**Comment by Shidersz** [comment]
@resslinger Ok, if there is no solution, lets just keep uploading coverage from the latest Laravel 8.x version. We can review this on the future...

**Comment by DanielMalmgren** [comment]
Did anything more happen here? I get the feeling we shouldn't hold our breath waiting for PHP8 compatibility in ocular, right?

**Comment by resslinger** [comment]
@DanielMalmgren The support for Laravel 9 exists, without waiting of this PR. We will add the support for ocular with Laravel 9, if the package was updated for the symfony 6 dependencies. So you can use Laravel 9.

**Comment by DanielMalmgren** [comment]
> @DanielMalmgren The support for Laravel 9 exists, without waiting of this PR. We will add the support for ocular with Laravel 9, if the package was updated for the symfony 6 dependencies. So you can use Laravel 9.

Thanks! I'm experiencing some problems so I thought you simply didn't have Laravel 9 support yet, but I'll submit separate issues for those problems.

**Comment by resslinger** [comment]
@DanielMalmgren @Shidersz I got feedback from scrutinizer. They have added symfony 6 support now. I will test the changes now.

**Comment by Shidersz** [comment]
@resslinger I manage to get this working, could you review it now?

**Comment by resslinger** [comment]
Perfect, we can merge it

**Pull request merged**
