### PR TITLE
Configuration property to enable/disable forgot password

### PR DESCRIPTION
**Pull request by josefelipetto**
Motivation: I had to create a simple login without any additional feature, like 'Forgot Password' or 'Create User'. I could disable create user but not the forgot password section. I didnt want to publish all the views just because of that feature, so i thought it's going to be great if the user has the ability to enable/disable that section.

### CODE REVIEW

**Comment by lacodimizer** [comment]
Thanks for your PR. Can you please add a config for the register link too?

**Comment by Shidersz** [comment]
There is already a configuration option to disable the registration of a new user, it is documented on [Section 6.9](https://github.com/jeroennoten/Laravel-AdminLTE#69-urls):

> **register_url**: Changes the register link or if set false it will hide.

To disable the **Forgot password** link one can follow the same logic, i.e, when the option:

> password_reset_url: Changes the password reset url

is set to `false` the **Forgot password** link section could be hidden.

**Comment by Shidersz** [comment]
Sorry, my commentary do not means that the feature for hide the **Forgot password** link already exists, but it can be implemented that way.

**Comment by lacodimizer** [comment]
Comes with PR #538

**Pull request closed without merging**
